Fri, 09 Oct 2020 16:00:32 INFO     __init__       -- 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BrachioGraph started XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Fri, 09 Oct 2020 16:00:34 INFO     plot_file      -- Plot start
Fri, 09 Oct 2020 16:00:34 INFO     plot_file      -- Filename: images/crossa.json; Wait: 0; Interpolate: 10; Bounds: None
Fri, 09 Oct 2020 16:00:34 ERROR    main           -- ERROR
Traceback (most recent call last):
  File "main.py", line 45, in main
    bg.plot_file("images/" + filename)
  File "/home/pi/BrachioGraph/brachiograph.py", line 179, in plot_file
    with open(filename, "r") as line_file:
FileNotFoundError: [Errno 2] No such file or directory: 'images/crossa.json'
Fri, 09 Oct 2020 16:00:34 INFO     main           -- 0:00:02
